name: setlists

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.9
  - numpy
  - pip
  - pandas
  - matplotlib
  - seaborn
  - requests
  - bs4
  - pypdf2
  - beautifulsoup4
  - spotipy
  - spacy
